Repository banzakk/backend, pull requests merged in 2024-01, with the labels that each got.

#31 improve:docs
  Banzzak.png
  README.md
Labels: 문서 수정

#33 refactor: WhisperStatus값 추가
  src/whisper-status/entities/whisper-status.entity.ts
  src/whispers/entities/whisper.entity.ts
  src/whispers/whispers.service.ts
Labels: 리팩토링, 버그 수정

#34 docs: api 문서 추가
  README.md
Labels: 문서 수정

#36 hotfix: userProfile 및 / 라우터 토큰 검증 삭제
  src/app.controller.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: 기능 개선, 버그 수정

#37 feat: 타임라인 조회 추가
  src/follows/follows.service.ts
  src/user-whisper/user-whisper.controller.ts
  src/user-whisper/user-whisper.module.ts
  src/user-whisper/user-whisper.service.ts
Labels: 기능 구현

#38 feat: whisper 삭제 추가
  src/whispers/whispers.controller.ts
  src/whispers/whispers.module.ts
  src/whispers/whispers.service.ts
Labels: 기능 구현

#39 refactor: 삭제된 위스퍼 조회 되지않도록 수정
  src/user-whisper/user-whisper.controller.ts
  src/user-whisper/user-whisper.service.ts
Labels: 리팩토링

#40 refactor: res data 수정
  src/user-whisper/user-whisper.service.ts
Labels: 리팩토링

#41 feat: 좋아요 기능 추가
  src/app.module.ts
  src/like/entities/like.entity.ts
  src/like/like.module.ts
  src/like/like.service.spec.ts
  src/like/like.service.ts
  src/models/index.ts
  src/users/entities/user.entity.ts
  src/users/users.service.ts
  src/whispers/entities/whisper.entity.ts
  src/whispers/whispers.controller.ts
  src/whispers/whispers.module.ts
  src/whispers/whispers.service.ts
Labels: 기능 구현

#42 feat: 좋아요 해제 기능 추가
  src/like/like.service.ts
  src/whispers/whispers.controller.ts
  src/whispers/whispers.service.ts
Labels: 기능 구현

#43 fix: resultQuery 조건 수정
  src/user-whisper/user-whisper.service.ts
Labels: 기능 개선

#44 feat: 위스퍼 상세 조회 기능 구현
  src/whispers/whispers.controller.ts
  src/whispers/whispers.service.ts
Labels: 기능 구현
